hwi_oauth:
    connect:
        account_connector: mws_user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            facebook: facebookId

    resource_owners:
        facebook:
            type:                facebook
            client_id:           %client_id%
            client_secret:       %client_secret%
            # options:
            #     display: popup #dialog is optimized for popup window
            scope:         "email"
            infos_url:     "https://graph.facebook.com/me?fields=username,first_name,last_name,email,picture.type(square)"
            paths:
                email:          email
                profilepicture: picture.data.url