sistema_hack:
    resource: "@SistemaHackBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

mw_simple_admin_crud:
    resource: "@MWSimpleAdminCrudBundle/Controller/"
    type:     annotation
    prefix:   /admin

sistema_user:
    resource: "@SistemaUserBundle/Controller/"
    type:     annotation
    prefix:   /

sistema_facebook_api:
    resource: "@SistemaFacebookApiBundle/Controller/"
    type:     annotation
    prefix:   /
#CONNECT FACEBOOK
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /connect

facebook_login:
    pattern: /login/check-facebook

logout:
    path: /logout